### ISSUE TITLE
Kubernetes Object Definitions

### ISSUE THREAD

**Issue by TannerYoung** [yesinteractive/dadjokes#1]
It seems worth putting in a full "prod" example on kubernetes with service mesh configuration. Was really hoping this would be a simple `git clone && kubectl apply` and then it's up and running.

That's what I initially interpreted when I saw "Microservice of dad jokes for k8s, docker, kong, istio, kuma, etc"

Anyway just that that would be really cool to see - cool repo regardless :)

**Comment by yesinteractive** [comment]
Great point @TannerYoung . I'll share some examples of yaml's that define the service, endpoints and/or ingress.

**Comment by yesinteractive** [comment]
kubectl examples have been added in the examples directory.
